name: Gh-Pages

on:
  push:
    branches: [preview]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.0

      # Get dependencies and build web
      - run: flutter pub get
      - run: flutter build web --release

      # Deploy to gh-pages
      - uses: bluefireteam/flutter-gh-pages@v9
        with:
          baseHref: /E-commerce-App-with-Backend/
